# Generated by Django 4.0.5 on 2022-06-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(verbose_name='')),
                ('discp', models.TextField(verbose_name='')),
                ('image', models.ImageField(upload_to=None)),
            ],
        ),
    ]
